# Generated by Django 5.1.1 on 2024-10-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_view_category', 'Can view category')]},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_manage_discounts', 'Can manage discounts'), ('can_manage_orders', 'Can manage orders'), ('can_manage_customers', 'Can manage customer information'), ('can_view_customer_info', 'Can view customer information'), ('can_assist_issues', 'Can assist with issues'), ('can_view_orders', 'Can view orders'), ('can_read_only', 'Can read-only access'), ('can_manage_promotions', 'Can manage promotions'), ('can_manage_product_visibility', 'Can manage product visibility'), ('can_manage_inventory', 'Can manage inventory'), ('can_update_product_quantity', 'Can update product quantity')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_manage_inventory', 'Can manage inventory'), ('can_update_product_quantity', 'Can update product quantity'), ('can_manage_product_visibility', 'Can manage product visibility'), ('can_view_product', 'Can view product')]},
        ),
    ]
