# Generated by Django 5.1.1 on 2024-10-09 08:40

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_manage_everything', 'Can manage everything in the system'), ('can_manage_products', 'Can manage products (add, edit, delete)'), ('can_edit_content', 'Can edit content but cannot delete'), ('can_manage_discounts', 'Can manage discounts'), ('can_manage_orders', 'Can manage orders'), ('can_manage_customers', 'Can manage customer information'), ('can_view_customer_info', 'Can view customer information'), ('can_assist_issues', 'Can assist with customer issues'), ('can_view_orders', 'Can view orders'), ('can_read_only', 'Can only view data'), ('can_manage_promotions', 'Can manage promotions and discounts'), ('can_manage_product_visibility', 'Can manage product visibility'), ('can_manage_inventory', 'Can manage inventory'), ('can_update_product_quantity', 'Can update product quantity')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_manage_orders', 'Can manage orders'), ('can_view_order', 'Can view order')]},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
