# Generated by Django 5.1.1 on 2024-10-15 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_view_category', 'Can view category')]},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_manage_everything', 'Can manage everything in the system'), ('can_manage_products', 'Can manage products (add, edit, delete)'), ('can_edit_content', 'Can edit content but cannot delete'), ('can_manage_discounts', 'Can manage discounts'), ('can_manage_orders', 'Can manage orders'), ('can_manage_customers', 'Can manage customer information'), ('can_view_customer_info', 'Can view customer information'), ('can_assist_issues', 'Can assist with customer issues'), ('can_view_orders', 'Can view orders'), ('can_read_only', 'Can only view data'), ('can_manage_promotions', 'Can manage promotions and discounts'), ('can_manage_product_visibility', 'Can manage product visibility'), ('can_manage_inventory', 'Can manage inventory'), ('can_update_product_quantity', 'Can update product quantity')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_manage_orders', 'Can manage orders'), ('can_view_order', 'Can view order')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_manage_inventory', 'Can manage inventory'), ('can_update_product_quantity', 'Can update product quantity'), ('can_manage_product_visibility', 'Can manage product visibility'), ('can_view_product', 'Can view product')]},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
